import random
from typing import List


TAMA_CENTER_LINE_CODE = 246
TAMA_CENTER_STATION_CODE = 31
TAMA_CENTER = [TAMA_CENTER_LINE_CODE, TAMA_CENTER_STATION_CODE]

CHUO_MEISEI_LINE_CODE = 246
CHUO_MEISEI_STATION_CODE = 37
CHUO_MEISEI = [CHUO_MEISEI_LINE_CODE, CHUO_MEISEI_STATION_CODE]

TAKAHATAFUDO_LINE_CODE = 197
TAKAHATAFUDO_STATION_CODE = 29
TAKAHATAFUDO = [TAKAHATAFUDO_LINE_CODE, TAKAHATAFUDO_STATION_CODE]

TACHIKAWA_LINE_CODE = 3
TACHIKAWA_STATION_CODE = 34
TACHIKAWA = [TACHIKAWA_LINE_CODE, TACHIKAWA_STATION_CODE]

SHINJUKU_LINE_CODE = 37
SHINJUKU_STATION_CODE = 10
SHINJUKU = [SHINJUKU_LINE_CODE, SHINJUKU_STATION_CODE]

HACHIOJI_LINE_CODE = 3
HACHIOJI_STATION_CODE = 39
HACHIOJI = [HACHIOJI_LINE_CODE, HACHIOJI_STATION_CODE]

FUCHU_LINE_CODE = 197
FUCHU_STATION_CODE = 24
FUCHU = [FUCHU_LINE_CODE, FUCHU_STATION_CODE]

CHOFU_LINE_CODE = 197
CHOFU_STATION_CODE = 18
CHOFU = [CHOFU_LINE_CODE, CHOFU_STATION_CODE]

TOKYO_LINE_CODE = 1
TOKYO_STATION_CODE = 1
TOKYO = [TOKYO_LINE_CODE, TOKYO_STATION_CODE]

MACHIDA_LINE_CODE = 29
MACHIDA_STATION_CODE = 30
MACHIDA = [MACHIDA_LINE_CODE, MACHIDA_STATION_CODE]

KIYOSE_LINE_CODE = 186
KIYOSE_STATION_CODE = 20
KIYOSE = [KIYOSE_LINE_CODE, KIYOSE_STATION_CODE]

TENNOUZUAIRU_LINE_CODE = 130
TENNOUZUAIRU_STATION_CODE = 6
TENNOUZUAIRU = [TENNOUZUAIRU_LINE_CODE, TENNOUZUAIRU_STATION_CODE]

HARAJUKU_LINE_CODE = 37
HARAJUKU_STATION_CODE = 8
HARAJUKU = [HARAJUKU_LINE_CODE, HARAJUKU_STATION_CODE]


station_codes = [
    TAMA_CENTER,
    CHUO_MEISEI,
    TAKAHATAFUDO,
    TACHIKAWA,
    SHINJUKU,
    HACHIOJI,
    FUCHU,
    CHOFU,
    TOKYO,
    MACHIDA,
    KIYOSE,
    TENNOUZUAIRU,
    HARAJUKU,
]


def get_cyberne_random_station_codes() -> List[List[int]]:
    """
    station_codesからランダムで2つ取得する
    :return:
    """
    return random.sample(station_codes, 2)


if __name__ == '__main__':
    print(get_cyberne_random_station_codes())