import random
from typing import List


TAMA_CENTER_LINE_CODE = 246
TAMA_CENTER_STATION_CODE = 31
TAMA_CENTER = [TAMA_CENTER_LINE_CODE, TAMA_CENTER_STATION_CODE]

CHUO_MEISEI_LINE_CODE = 246
CHUO_MEISEI_STATION_CODE = 37
CHUO_MEISEI = [CHUO_MEISEI_LINE_CODE, CHUO_MEISEI_STATION_CODE]

TAKAHATAFUDO_LINE_CODE = 197
TAKAHATAFUDO_STATION_CODE = 29
TAKAHATAFUDO = [TAKAHATAFUDO_LINE_CODE, TAKAHATAFUDO_STATION_CODE]

TACHIKAWA_LINE_CODE = 3
TACHIKAWA_STATION_CODE = 34
TACHIKAWA = [TACHIKAWA_LINE_CODE, TACHIKAWA_STATION_CODE]

SHINJUKU_LINE_CODE = 37
SHINJUKU_STATION_CODE = 10
SHINJUKU = [SHINJUKU_LINE_CODE, SHINJUKU_STATION_CODE]

HACHIOJI_LINE_CODE = 3
HACHIOJI_STATION_CODE = 39
HACHIOJI = [HACHIOJI_LINE_CODE, HACHIOJI_STATION_CODE]

FUCHU_LINE_CODE = 197
FUCHU_STATION_CODE = 24
FUCHU = [FUCHU_LINE_CODE, FUCHU_STATION_CODE]

CHOFU_LINE_CODE = 197
CHOFU_STATION_CODE = 18
CHOFU = [CHOFU_LINE_CODE, CHOFU_STATION_CODE]

TOKYO_LINE_CODE = 1
TOKYO_STATION_CODE = 1
TOKYO = [TOKYO_LINE_CODE, TOKYO_STATION_CODE]

MACHIDA_LINE_CODE = 29
MACHIDA_STATION_CODE = 30
MACHIDA = [MACHIDA_LINE_CODE, MACHIDA_STATION_CODE]

KIYOSE_LINE_CODE = 186
KIYOSE_STATION_CODE = 20
KIYOSE = [KIYOSE_LINE_CODE, KIYOSE_STATION_CODE]

TENNOUZUAIRU_LINE_CODE = 130
TENNOUZUAIRU_STATION_CODE = 6
TENNOUZUAIRU = [TENNOUZUAIRU_LINE_CODE, TENNOUZUAIRU_STATION_CODE]

HARAJUKU_LINE_CODE = 37
HARAJUKU_STATION_CODE = 8
HARAJUKU = [HARAJUKU_LINE_CODE, HARAJUKU_STATION_CODE]

OKUTAMA = [24, 61]
KOMIYA = [29, 43]
RIZOTO = [238, 2]
AZABU = [231, 40]
OSHIAGE = [230, 53]
SHIBUYA = [230, 33]
ROPPONGI = [228, 57]
ASAKUSA = [227, 44]
MITAKADAI = [203, 15]
SAKURAJOUSUI = [197, 8]
OUJI = [2, 13]
AKABANE = [2, 16]
MAIHAMA = [63, 8]
DAIBA = [130, 73]
TOYOSU = [130, 86]
KAMATA = [207, 18]
HANEDA = [214, 6]
OOTORII = [214, 3]
TAMAGAWA = [206, 25]
NIKOTAMA = [210, 14]
KOMAE = [224, 17]
SHIBASAKI = [197, 15]
MUSASHINODAI = [197, 21]
NAKAGAWARA = [197, 26]
TUKUSHINO = [208, 55]
KAWAI = [24, 56]
GUNHANTAKE = [24, 52]
HIGASHIMURAYAMA = [189, 25]
MUSASHIYAMATO = [192, 10]
TAKAOSANGUCHI = [200, 7]
HAZAMA = [200, 5]
YAMADA = [200, 3]
OUME = [24, 46]
OZAKU = [24, 42]
FUSSA = [24, 39]
MUSASHIITSUKAICHI = [36, 8]
AKIGAWA = [36, 4]
KITASENJU = [5, 6]
RYOGOKU = [22, 4]
KINSHICHO = [22, 6]
HIRAI = [22, 8]
OOSHIMA = [241, 17]
TOHYOUCHO = [228, 82]
TSUKISHIMA = [242, 10]
KACHIDOKI = [242, 12]
SHIRAKAWA = [242, 6]
IIDABASHI = [243, 17]
TABATA = [2, 11]
UENO = [2, 6]
KASUGA = [240, 54]
ICHIGAYA = [3, 7]
NAGATACHO = [227, 120]
SAKURADAMON = [227, 121]
WASEDA = [228, 71]
OCHIAI = [228, 67]
HIKARIGAOKA = [242, 54]
SHIMOAKATSUKA = [169, 9]
OOIZUMIGAKUEN = [186, 15]
TORITSUDAIGAKU = [206, 31]
YUTENJI = [206, 33]
TODOROKI = [208, 33]
THITOSEHUNABASHI = [224, 12]


station_codes = [
    # TAMA_CENTER,
    CHUO_MEISEI,
    TAKAHATAFUDO,
    TACHIKAWA,
    SHINJUKU,
    HACHIOJI,
    FUCHU,
    CHOFU,
    TOKYO,
    MACHIDA,
    KIYOSE,
    TENNOUZUAIRU,
    HARAJUKU,
    OKUTAMA,
    KOMIYA,
    RIZOTO,
    AZABU,
    OSHIAGE,
    SHIBUYA,
    ROPPONGI,
    ASAKUSA,
    MITAKADAI,
    SAKURAJOUSUI,
    OUJI,
    AKABANE,
    MAIHAMA,
    DAIBA,
    TOYOSU,
    KAMATA,
    HANEDA,
    OOTORII,
    TAMAGAWA,
    NIKOTAMA,
    KOMAE,
    SHIBASAKI,
    MUSASHINODAI,
    NAKAGAWARA,
    TUKUSHINO,
    KAWAI,
    GUNHANTAKE,
    HIGASHIMURAYAMA,
    MUSASHIYAMATO,
    TAKAOSANGUCHI,
    HAZAMA,
    YAMADA,
    OUME,
    OZAKU,
    FUSSA,
    MUSASHIITSUKAICHI,
    AKIGAWA,
    KITASENJU,
    RYOGOKU,
    KINSHICHO,
    HIRAI,
    OOSHIMA,
    TOHYOUCHO,
    TSUKISHIMA,
    KACHIDOKI,
    SHIRAKAWA,
    IIDABASHI,
    TABATA,
    UENO,
    KASUGA,
    ICHIGAYA,
    NAGATACHO,
    SAKURADAMON,
    WASEDA,
    OCHIAI,
    HIKARIGAOKA,
    SHIMOAKATSUKA,
    OOIZUMIGAKUEN,
    TORITSUDAIGAKU,
    YUTENJI,
    TODOROKI,
    THITOSEHUNABASHI,
]


def get_cyberne_random_station_codes() -> List[List[int]]:
    """
    station_codesからランダムで2つ取得する
    :return:
    """
    return random.sample(station_codes, 2)


if __name__ == '__main__':
    print(get_cyberne_random_station_codes())